// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzxyaqlvayldlnvuwolc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6eHlhcWx2YXlsZGxudnV3b2xjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjAxOTAsImV4cCI6MjA3NDM5NjE5MH0.mX6_rBGEFp6o8LHC-XMvqFY5zkoUsRs2JrQZROcPlgM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});